baseURL = "https://readonly.dev.br/"
languageCode = "en-us"
title = "readonly.dev.br"
theme = "hugo-bearblog"
author = "Lenon Marcel"
copyright = "Copyright © 2020, Lenon Marcel."

[params]
  hideMadeWithLine = true
